# Generated by Django 4.2 on 2023-04-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soap_app', '0003_rename_first_name_user_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
    ]
